const REPORT_FILED_VIEW_MODE = {
	'VIEW' : 'VIEW',
	'EDIT' : 'EDIT'
};

const STAFF_ROLES = {
	'MEMBER_OF_STAFF'	: 'MEMBER_OF_STAFF',
	'COACH'				: 'COACH'
};

module.exports.REPORT_FILED_VIEW_MODE	= REPORT_FILED_VIEW_MODE;
module.exports.STAFF_ROLES				= STAFF_ROLES;