const FIXTURE_LIST_MODE = {
	'RECENT'	: 'RECENT',
	'UPCOMING'	: 'UPCOMING'
};

const BIGSCREEN_STATES_MODE = {
	'RECENT'			: 'RECENT',
	'UPCOMING'			: 'UPCOMING',
	'EVENT_HIGHLIGHT'	: 'EVENT_HIGHLIGHT',
	'HIGHLIGHT'			: 'HIGHLIGHT'
};

module.exports.FIXTURE_LIST_MODE		= FIXTURE_LIST_MODE;
module.exports.BIGSCREEN_STATES_MODE	= BIGSCREEN_STATES_MODE;