const  	TypeText 			= require('module/ui/form/types/text'),
		TypeNumber 			= require('module/ui/form/types/number'),
        TypeHidden 			= require('module/ui/form/types/hidden'),
        TypePassword 		= require('module/ui/form/types/password'),
		TypeArea 			= require('module/ui/form/types/area'),
		TypeAutocomplete 	= require('module/ui/form/types/autocomplete'),
		TypeConfirmText 	= require('module/ui/form/types/confirm_text'),
		TypeDate 			= require('module/ui/form/types/form-date'),
		TypeDateTime		= require('module/ui/form/types/form-datetime'),
		TypeColors 			= require('module/ui/form/types/colors'),
		TypeSelect 			= require('module/ui/form/types/select'),
		TypeRadio 			= require('module/ui/form/types/radio'),
		TypePhone 			= require('module/ui/form/types/phone'),
		TypeDrop 			= require('module/ui/form/types/dropdown'),
		TypeTextArea 		= require('module/ui/form/types/textarea'),
		TypeTermsCheckbox 	= require('module/ui/form/types/terms_checkbox'),
		TypeImageFileUpload	= require('module/ui/form/types/imageFileType'),
		TypeCheckbox 		= require('module/ui/form/types/checkbox'),
		typeList = {};

// Input element type list
typeList['text'] 				= TypeText;
typeList['number'] 				= TypeNumber;
typeList['password'] 			= TypePassword;
typeList['confirmText'] 		= TypeConfirmText;
typeList['area'] 				= TypeArea;
typeList['autocomplete'] 		= TypeAutocomplete;
typeList['date'] 				= TypeDate;
typeList['datetime'] 			= TypeDateTime;
typeList['colors'] 				= TypeColors;
typeList['select'] 				= TypeSelect;
typeList['radio'] 				= TypeRadio;
typeList['hidden'] 				= TypeHidden;
typeList['phone'] 				= TypePhone;
typeList['dropdown'] 			= TypeDrop;
typeList['textarea'] 			= TypeTextArea;
typeList['imageFile']			= TypeImageFileUpload;
typeList['terms'] 				= TypeTermsCheckbox;
typeList['checkbox'] 			= TypeCheckbox;

module.exports = typeList;
