const ACCESS_PRESETS_SERVER_VALUE = {
	'PUBLIC'					: 'PUBLIC',
	'PRIVATE'					: 'PRIVATE',
	'ALL_PARTICIPANT_PARENTS'	: 'ALL_PARTICIPANT_PARENTS'
};

const ACCESS_PRESET_LIST_MANAGER = {
	'PUBLIC'					: 'Public',
	'PRIVATE'					: 'Private',
	'ALL_PARTICIPANT_PARENTS'	: 'Team members'
};

const ACCESS_PRESET_LIST_PARENT = {
	'PRIVATE'					: 'Private',
	'ALL_PARTICIPANT_PARENTS'	: 'Team members'
};

module.exports.ACCESS_PRESETS_SERVER_VALUE	= ACCESS_PRESETS_SERVER_VALUE;
module.exports.ACCESS_PRESET_LIST_MANAGER	= ACCESS_PRESET_LIST_MANAGER;
module.exports.ACCESS_PRESET_LIST_PARENT	= ACCESS_PRESET_LIST_PARENT;